package com.cmeza.spring.excel.repository.support.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum TableStyleValue {
    NONE(""),
    TABLE_STYLE_LIGHT_1("TableStyleLight1"),
    TABLE_STYLE_LIGHT_2("TableStyleLight2"),
    TABLE_STYLE_LIGHT_3("TableStyleLight3"),
    TABLE_STYLE_LIGHT_4("TableStyleLight4"),
    TABLE_STYLE_LIGHT_5("TableStyleLight5"),
    TABLE_STYLE_LIGHT_6("TableStyleLight6"),
    TABLE_STYLE_LIGHT_7("TableStyleLight7"),
    TABLE_STYLE_LIGHT_8("TableStyleLight8"),
    TABLE_STYLE_LIGHT_9("TableStyleLight9"),
    TABLE_STYLE_LIGHT_10("TableStyleLight10"),
    TABLE_STYLE_LIGHT_11("TableStyleLight11"),
    TABLE_STYLE_LIGHT_12("TableStyleLight12"),
    TABLE_STYLE_LIGHT_13("TableStyleLight13"),
    TABLE_STYLE_LIGHT_14("TableStyleLight14"),
    TABLE_STYLE_LIGHT_15("TableStyleLight15"),
    TABLE_STYLE_LIGHT_16("TableStyleLight16"),
    TABLE_STYLE_LIGHT_17("TableStyleLight17"),
    TABLE_STYLE_LIGHT_18("TableStyleLight18"),
    TABLE_STYLE_LIGHT_19("TableStyleLight19"),
    TABLE_STYLE_LIGHT_20("TableStyleLight20"),
    TABLE_STYLE_LIGHT_21("TableStyleLight21"),
    TABLE_STYLE_MEDIUM_1("TableStyleMedium1"),
    TABLE_STYLE_MEDIUM_2("TableStyleMedium2"),
    TABLE_STYLE_MEDIUM_3("TableStyleMedium3"),
    TABLE_STYLE_MEDIUM_4("TableStyleMedium4"),
    TABLE_STYLE_MEDIUM_5("TableStyleMedium5"),
    TABLE_STYLE_MEDIUM_6("TableStyleMedium6"),
    TABLE_STYLE_MEDIUM_7("TableStyleMedium7"),
    TABLE_STYLE_MEDIUM_8("TableStyleMedium8"),
    TABLE_STYLE_MEDIUM_9("TableStyleMedium9"),
    TABLE_STYLE_MEDIUM_10("TableStyleMedium10"),
    TABLE_STYLE_MEDIUM_11("TableStyleMedium11"),
    TABLE_STYLE_MEDIUM_12("TableStyleMedium12"),
    TABLE_STYLE_MEDIUM_13("TableStyleMedium13"),
    TABLE_STYLE_MEDIUM_14("TableStyleMedium14"),
    TABLE_STYLE_MEDIUM_15("TableStyleMedium15"),
    TABLE_STYLE_MEDIUM_16("TableStyleMedium16"),
    TABLE_STYLE_MEDIUM_17("TableStyleMedium17"),
    TABLE_STYLE_MEDIUM_18("TableStyleMedium18"),
    TABLE_STYLE_MEDIUM_19("TableStyleMedium19"),
    TABLE_STYLE_MEDIUM_20("TableStyleMedium20"),
    TABLE_STYLE_MEDIUM_21("TableStyleMedium21"),
    TABLE_STYLE_MEDIUM_22("TableStyleMedium22"),
    TABLE_STYLE_MEDIUM_23("TableStyleMedium23"),
    TABLE_STYLE_MEDIUM_24("TableStyleMedium24"),
    TABLE_STYLE_MEDIUM_25("TableStyleMedium25"),
    TABLE_STYLE_MEDIUM_26("TableStyleMedium26"),
    TABLE_STYLE_MEDIUM_27("TableStyleMedium27"),
    TABLE_STYLE_MEDIUM_28("TableStyleMedium28"),
    TABLE_STYLE_DARK_1("TableStyleDark1"),
    TABLE_STYLE_DARK_2("TableStyleDark2"),
    TABLE_STYLE_DARK_3("TableStyleDark3"),
    TABLE_STYLE_DARK_4("TableStyleDark4"),
    TABLE_STYLE_DARK_5("TableStyleDark5"),
    TABLE_STYLE_DARK_6("TableStyleDark6"),
    TABLE_STYLE_DARK_7("TableStyleDark7"),
    TABLE_STYLE_DARK_8("TableStyleDark8"),
    TABLE_STYLE_DARK_9("TableStyleDark9"),
    TABLE_STYLE_DARK_10("TableStyleDark10"),
    TABLE_STYLE_DARK_11("TableStyleDark11");

    final String value;
}
